-- 1. Create the 'active_trips' table
create table public.active_trips (
  id bigint generated by default as identity primary key,
  driver_id uuid references auth.users not null,
  route_name text not null,
  latitude double precision not null,
  longitude double precision not null,
  last_updated timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Enable Row Level Security (RLS)
alter table public.active_trips enable row level security;

-- 3. Create Policies

-- Policy 1: Allow everyone (authenticated or anonymous) to view bus locations
create policy "Enable read access for all users"
on public.active_trips
for select
using (true);

-- Policy 2: Allow authenticated users to insert their own location
-- (The C# app ensures only drivers call this, but you can add extra checks here if needed)
create policy "Enable insert for users based on user_id"
on public.active_trips
for insert
with check (auth.uid() = driver_id);

-- Policy 3: Allow users to update their own location
create policy "Enable update for users based on user_id"
on public.active_trips
for update
using (auth.uid() = driver_id)
with check (auth.uid() = driver_id);

-- Policy 4: Allow users to delete their own location (Stop Sharing)
create policy "Enable delete for users based on user_id"
on public.active_trips
for delete
using (auth.uid() = driver_id);

-- 4. Enable Realtime
-- This is crucial for the "Live Map" feature to work
alter publication supabase_realtime add table public.active_trips;
